LmazonBookStore/Controllers/CheckOutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LmazonBookStore.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LmazonBookStore.Controllers
{
    public class CheckOutController : Controller
    {
        private ICheckOutRepository repo { get; set; }

        private Basket basket { get; set; }

        public CheckOutController(ICheckOutRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        // GET: /<controller>/
        [HttpGet]
        public IActionResult CheckOut()
        {
            return View(new CheckOut());
        }

        [HttpPost]
        public IActionResult CheckOut(CheckOut checkout)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                checkout.Lines = basket.Items.ToArray();
                repo.SaveCheckOut(checkout);
                basket.ClearBasket();

                return RedirectToPage("/CheckOutCompleted");
            }
            else
            {
                return View();
            }

            IdentitySeedData.num = IdentitySeedData.num + 5;

        }
    }
}

LmazonBookStore/Pages/CheckOutCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LmazonBookStore.Pages
{
    public class CheckOutCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

LmazonBookStore/Pages/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LmazonBookStore.Infrastrusture;
using LmazonBookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LmazonBookStore.Pages
{
    public class ShoppingCartModel : PageModel
    {

        private IBookStoreRepository repo { get; set; }

        public ShoppingCartModel (IBookStoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public Basket basket { get; set; }

        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Books b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            //basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();

            basket.AddItem(b, 1);

            //HttpContext.Session.SetJson("basket", basket);

            return RedirectToPage(new {ReturnUrl = returnUrl });

        }

        //A funtion to remove items from the cart
        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Books.BookId == bookId).Books);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

LmazonBookStore/Pages/CheckOutCompleted.cshtml
@page
@model LmazonBookStore.Pages.CheckOutCompletedModel
@{
}

<div class="text-center">
    <h2>Thanks! Your order will be prepared within the next hour.</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

LmazonBookStore/Pages/ShoppingCart.cshtml
@page
@model LmazonBookStore.Pages.ShoppingCartModel
@{
}

<h2>Shopping Cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Price</th>
            @*<th>Total Books</th>*@
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td class="text-left">@i.Books.Title</td>
                <td class="text-center">@i.Quantity</td>
                <td class="text-right">@i.Books.Price.ToString("$#,##0.00")</td>
                <td class="text-right">@((i.Quantity * i.Books.Price).ToString("$#,##0.00"))</td>

                <td class="text-center">
                    @*A post method that remove an item in the cart, need to call a function from the ShoppingCart to do the work*@
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Books.BookId"/>
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl"/>
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total Price: </td>
            <td class="text-right">
                @Model.basket.CalcualteTotal().ToString("$#,##0.00")
            </td>
        </tr>
    </tfoot>

    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total Book(s): </td>
            <td class="text-right">
                @Model.basket.TotalBook()
            </td>
        </tr>
    </tfoot>

</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="CheckOut" asp-action="Checkout">Checkout</a>
</div>

LmazonBookStore/Pages/_ShoppingCartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        YUZE
    </div>



    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>