LmazonBookStore/Components /CartSummaryViewComponent.cs
using System;
using LmazonBookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace LmazonBookStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket cart;
        public CartSummaryViewComponent(Basket cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

LmazonBookStore/Components /TypesViewComponent.cs
using System;
using System.Linq;
using LmazonBookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace LmazonBookStore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookStoreRepository repo { get; set; }

        public TypesViewComponent (IBookStoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {

            ViewBag.SelectedCategory = RouteData?.Values["category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }


    }
}

LmazonBookStore/Views/Shared/ProjectSummary.cshtml
@{
}

@model Books

<div class="card card-outline-primary m-1 p-1">

    <div class="bg-light p-1">
        <h4>@Model.Title</h4>

        <div class="bg-faded p-1">
            <h4>
                <span class="badge badge-pill badge-primary" style="float:right">
                    <small>USD$ @Model.Price</small>
                </span>
            </h4>
        </div>
    </div>

    <div class="card-text p-1">Author: @Model.Author</div>
    <div class="card-text p-1">Publisher: @Model.Publisher</div>
    <div class="card-text p-1">ISBN: @Model.Isbn</div>
    <div class="card-text p-1">Classification: @Model.Classification</div>
    <div class="card-text p-1">Category: @Model.Category</div>
    <div class="card-text p-1">Number of Page: @Model.PageCount pages</div>

    <form method="post" asp-page="/ShoppingCart">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Shopping Cart</button>
        </span>

    </form>

</div>

LmazonBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="icon" href="https://media.geeksforgeeks.org/wp-content/cdn-uploads/gfg_200X200.png"
          type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>

<body>
    <header>
        <div class="bg-dark text-white p-2">
            <div class="container-fluid">
                <div class="row">
                    <div class="col navbar-brand">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Yuze</a>
                    </div>

                    <div class="col-6 text-right">
                        <vc:cart-summary />
                    </div>
                </div>
            </div>
        </div>
    </header>

    @*move text*@
    <marquee direction="right"
             behavior="alternate"
             style="border:BLACK 2px SOLID">
        Welcome to Yuze Book Store :)
    </marquee>
    @*Gif pic*@
    <img src="http://i.stack.imgur.com/SBv4T.gif" alt="this slowpoke moves" width="250" />


    <div class="row m-1 p-1">

        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - YUZE BOOK STORE - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
</body>
</html>